POST http://127.0.0.1:8080/v1/compile/command
Content-Type: application/json
Connection: close

{
  "files": [
    {
      "name": "my/folder/File.kt",
      "text": "package io.magnaura\n\nfun say(args: Array<String>): String {\n  return \"239\"\n}\n fun main(args: Array<String>) {\n    println(\"Hello world.\")\n}"
    }
  ]
}

###
