POST http://127.0.0.1:8080/v1/compile
Content-Type: application/json
Connection: close

{
  "context": "fun squareDiff(a: Int, b: Int): Int {\n  return a * a - b * b\n}",
  "command": "94.5 - squareDiff(9, 7)"
}

###
