POST http://127.0.0.1:8080/compiler
Content-Type: application/json
Connection: close

{
  "files": [
    {
      "name": "File.kt",
      "text": "fun main(args: Array<String>) {\n    println(\"Hello world.\")\n}"
    }
  ]
}